In [1]:
import pandas as pd
import requests

# P1

In [ ]:
file_url = "https://trafficdata.tii.ie/tfdaysreport.asp?sgid=XzOA8m4lr27P0HaO3_srSB&spid=47160F4E98FE&reportdate=2021-01-01&enddate=2021-01-31&dir=0&excel=1"

file_data = requests.get(file_url).content
# create the file in write binary mode, because the data we get from net is in binary
with open("file.xls", "wb") as file:
    file.write(file_data)

In [ ]:
data = pd.read_html('file.xls')
df = data[5]

In [ ]:
id = data[0][1][1]
id

'000000001282'

In [ ]:
df = df.iloc[:24, :-3]

In [ ]:
df.columns = [x[1] for x in df.columns]

In [ ]:
df

,Time,2021-01-01,2021-01-02,2021-01-03,2021-01-04,2021-01-05,2021-01-06,2021-01-07,2021-01-08,2021-01-09,...,2021-01-22,2021-01-23,2021-01-24,2021-01-25,2021-01-26,2021-01-27,2021-01-28,2021-01-29,2021-01-30,2021-01-31
0,00:00:00,13,7,11,7,13,17,25,18,23,...,14,22,19,12,23,9,12,10,32,10
1,01:00:00,15,5,11,1,4,15,13,8,21,...,21,14,12,8,10,15,16,16,12,7
2,02:00:00,8,11,4,6,9,13,9,11,12,...,17,25,12,14,24,11,18,15,14,6
3,03:00:00,3,10,11,11,33,13,23,22,101,...,11,88,14,19,8,18,27,15,86,10
4,04:00:00,5,14,10,20,22,24,28,23,62,...,20,62,42,28,21,52,21,20,35,28
5,05:00:00,26,59,47,112,112,128,143,128,67,...,129,75,82,150,125,133,131,135,74,76
6,06:00:00,135,202,255,751,794,811,804,791,266,...,901,349,302,835,1032,983,1004,947,362,306
7,07:00:00,124,195,181,1020,1021,983,955,1021,298,...,1253,303,276,1225,1266,1262,1298,1211,298,221
8,08:00:00,58,115,75,630,550,615,590,590,153,...,680,159,104,752,710,751,740,669,155,95
9,09:00:00,50,102,77,343,362,362,358,369,175,...,458,181,100,456,400,441,439,392,143,102
10,10:00:00,61,133,105,314,330,334,334,363,176,...,454,198,120,391,406,455,394,412,193,116
11,11:00:00,121,182,154,380,390,387,358,390,209,...,479,271,178,419,441,416,434,461,244,129
12,12:00:00,206,207,224,423,434,494,408,513,286,...,563,321,215,529,486,496,516,618,267,153
13,13:00:00,254,262,261,402,411,482,457,595,324,...,696,358,307,518,498,544,510,652,274,205
14,14:00:00,273,275,304,519,538,501,458,793,328,...,850,375,323,567,575,492,492,850,304,221
15,15:00:00,248,282,329,603,593,690,604,821,350,...,925,427,327,700,688,704,692,964,316,234
16,16:00:00,249,248,263,868,845,838,836,595,380,...,597,354,259,1127,1069,1042,1051,641,329,246
17,17:00:00,171,192,216,600,644,632,650,437,267,...,529,317,258,808,815,865,810,527,286,215
18,18:00:00,205,288,293,593,666,755,716,617,403,...,641,421,355,766,817,880,803,690,408,396
19,19:00:00,165,208,256,337,338,344,350,344,302,...,399,248,291,405,432,422,449,382,246,261
20,20:00:00,64,76,111,92,107,113,123,99,79,...,146,79,101,133,138,150,149,119,82,110
21,21:00:00,54,47,58,52,81,45,77,89,63,...,91,45,54,65,79,87,72,78,50,58
22,22:00:00,40,37,35,33,43,48,39,47,38,...,43,37,34,41,50,50,50,51,34,33
23,23:00:00,25,24,21,47,35,32,52,34,39,...,38,21,23,42,53,59,49,28,30,25

In [ ]:
df2 = df.melt(id_vars=['Time'], var_name=['Date'])
df2["datetime"] = df2["Date"] + " " + df2["Time"]
df2 = df2[["datetime", "value"]]
df2["datetime"] = df2["datetime"].astype("datetime64")
df2["id"] = id
df2 = df2[["datetime", "id", "value"]]
df2

               datetime            id value
0   2021-01-01 00:00:00  000000001282    13
1   2021-01-01 01:00:00  000000001282    15
2   2021-01-01 02:00:00  000000001282     8
3   2021-01-01 03:00:00  000000001282     3
4   2021-01-01 04:00:00  000000001282     5
..                  ...           ...   ...
739 2021-01-31 19:00:00  000000001282   261
740 2021-01-31 20:00:00  000000001282   110
741 2021-01-31 21:00:00  000000001282    58
742 2021-01-31 22:00:00  000000001282    33
743 2021-01-31 23:00:00  000000001282    25

[744 rows x 3 columns]

# P2

In [ ]:
location_df = pd.read_csv("/content/drive/MyDrive/Khoá luận tốt nghiệp/Dataset/Location_Official.csv")
# location_df = location_df[:2]
location_df

,Site Name,SgidSpid,Location
0,TMU N27 000.0 N,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=F9E3793B6432,"51.86242, -8.47908"
1,TMU N71 002.5 N,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=B8B7D4554595,"51.85265, -8.52882"
2,TMU N40 005.5 W,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=00CB482ECD32,"51.87619, -8.49964"
3,TMU N40 004.5 W,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=275F808BB259,"51.87567, -8.51047"
4,TMU N40 002.5 E,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=F5FD2E754102,"51.87281, -8.53436"
5,TMU N40 000.0 W,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=36F804B24689,"51.87636, -8.56072"
6,TMU N22 010.0 W,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=2E424106C30B,"51.88714, -8.56911"
7,TMU N22 000.0 E,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=E8051BC36A91,"51.894, -8.51757"
8,TMU N40 010.0 E,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=0020B40EAB83,"51.87488, -8.44783"
9,TMU N40 005.0 W,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=B4B084EBD8B7,"51.87942, -8.43249"
10,TMU N28 004.0 E,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=84A983003611,"51.85085, -8.41577"
11,TMU N28 001.0 S,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=55F77DFA0999,"51.87578, -8.41266"
12,TMU N40 010.0 W,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=5C82E9FCACEC,"51.88229, -8.4076"
13,TMU N40 015.0 W,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=7709C672BB02,"51.88825, -8.39061"
14,TMU N08 150.0 S,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=A78D2FA14505,"51.90461, -8.41296"
15,TMU N08 140.0 S,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=60BA7A8B5286,"51.90523, -8.39022"
16,TMU N25 000.0 E,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=DFA198C74264,"51.90728, -8.35638"
17,TMU M08 140.0 S,sgid=XZOA8M4LR27P0HAO3_SRSB&spid=2C9A6D4BA0E0,"51.9161, -8.38155"

In [ ]:
df = pd.DataFrame()

dict_date = {"thang1": ["2021-01-01", "2021-01-31"],
             "thang2": ["2021-02-01", "2021-02-28"],
             "thang3": ["2021-03-01", "2021-03-31"],
             "thang4": ["2021-04-01", "2021-04-30"],
             "thang5": ["2021-05-01", "2021-05-31"],
             "thang6": ["2021-06-01", "2021-06-30"],
             "thang7": ["2021-07-01", "2021-07-31"],
             "thang8": ["2021-08-01", "2021-08-31"],
             "thang9": ["2021-09-01", "2021-09-30"],
             "thang10": ["2021-10-01", "2021-10-31"],
             "thang11": ["2021-11-01", "2021-11-30"],
             "thang12": ["2021-12-01", "2021-12-31"],
             }

for i in range(len(location_df)):
  location = location_df["Location"][i]
  sgid_spid = location_df["SgidSpid"][i]
  print("Location " + str(i) + ": " + location_df["Site Name"][i])

  for k in dict_date:
    print(" ----- " + k)
    file_url = "https://trafficdata.tii.ie/tfdaysreport.asp?{}&reportdate={}&enddate={}&dir=0&excel=1".format(sgid_spid, dict_date[k][0], dict_date[k][1])
    file_data = requests.get(file_url).content
    # create the file in write binary mode, because the data we get from net is in binary
    with open("file.xls", "wb") as file:
        file.write(file_data)
    data = pd.read_html('file.xls')
    df2 = data[5]
    id = data[0][1][1]
    df2 = df2.iloc[:24, :-3]
    df2.columns = [x[1] for x in df2.columns]
    df2 = df2.melt(id_vars=['Time'], var_name=['Date'])
    df2["datetime"] = df2["Date"] + " " + df2["Time"]
    df2 = df2[["datetime", "value"]]
    df2["datetime"] = df2["datetime"].astype("datetime64")
    # df2["value"] = df2["value"].astype("int64")
    df2["id"] = id
    df2["location"] = location
    df2 = df2[["id", "datetime", "location", "value"]]
    df = pd.concat([df, df2], ignore_index=True)

df

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Khoá luận tốt nghiệp/Dataset/final_data.csv")
df

,id,datetime,location,value,irain,rain,itemp,temp,iwb,wetb,...,iwdsp,wdsp,iwddir,wddir,ww,w,sun,vis,clht,clamt
0,1271,2021-01-01 00:00:00,"51.86242, -8.47908",27.0,0,0.0,0,3.2,0,2.4,...,2,14,2,340,2,81,0.0,25000,999,3
1,1716,2021-01-01 00:00:00,"51.85265, -8.52882",31.0,0,0.0,0,3.2,0,2.4,...,2,14,2,340,2,81,0.0,25000,999,3
2,1403,2021-01-01 00:00:00,"51.87619, -8.49964",236.0,0,0.0,0,3.2,0,2.4,...,2,14,2,340,2,81,0.0,25000,999,3
3,1404,2021-01-01 00:00:00,"51.87567, -8.51047",156.0,0,0.0,0,3.2,0,2.4,...,2,14,2,340,2,81,0.0,25000,999,3
4,1405,2021-01-01 00:00:00,"51.87281, -8.53436",105.0,0,0.0,0,3.2,0,2.4,...,2,14,2,340,2,81,0.0,25000,999,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157675,1256,2021-12-31 23:00:00,"51.88825, -8.39061",273.0,0,0.0,0,11.0,0,10.6,...,2,17,2,160,10,22,0.0,6000,8,7
157676,1081,2021-12-31 23:00:00,"51.90461, -8.41296",262.0,0,0.0,0,11.0,0,10.6,...,2,17,2,160,10,22,0.0,6000,8,7
157677,200811,2021-12-31 23:00:00,"51.90523, -8.39022",261.0,0,0.0,0,11.0,0,10.6,...,2,17,2,160,10,22,0.0,6000,8,7
157678,20258,2021-12-31 23:00:00,"51.90728, -8.35638",268.0,0,0.0,0,11.0,0,10.6,...,2,17,2,160,10,22,0.0,6000,8,7
157679,20085,2021-12-31 23:00:00,"51.9161, -8.38155",80.0,0,0.0,0,11.0,0,10.6,...,2,17,2,160,10,22,0.0,6000,8,7

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157680 entries, 0 to 157679
Data columns (total 24 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        157680 non-null  int64
 1   datetime  157680 non-null  object
 2   location  157680 non-null  object
 3   value     157680 non-null  float64
 4   irain     157680 non-null  int64
 5   rain      157680 non-null  float64
 6   itemp     157680 non-null  int64
 7   temp      157680 non-null  float64
 8   iwb       157680 non-null  int64
 9   wetb      157680 non-null  float64
 10  dewpt     157680 non-null  float64
 11  vappr     157680 non-null  float64
 12  rhum      157680 non-null  int64
 13  msl       157680 non-null  float64
 14  iwdsp     157680 non-null  int64
 15  wdsp      157680 non-null  int64
 16  iwddir    157680 non-null  int64
 17  wddir     157680 non-null  int64
 18  ww        157680 non-null  int64
 19  w         157680 non-null  int64
 20  sun       157680 non-null  float64
 21  vis       157680 non-null  int64
 22  clht      157680 non-null  int64
 23  clamt     157680 non-null  int64
dtypes: float64(8), int64(14), object(2)
memory usage: 28.9+ MB

In [ ]:
df_null = df[df['value'].isnull()]
df_null

            id             datetime            location  value
2065      1271  2021-03-28 01:00:00  51.86242, -8.47908    NaN
19585     1403  2021-03-28 01:00:00  51.87619, -8.49964    NaN
28345     1404  2021-03-28 01:00:00  51.87567, -8.51047    NaN
37105     1405  2021-03-28 01:00:00  51.87281, -8.53436    NaN
45865     1255  2021-03-28 01:00:00  51.87636, -8.56072    NaN
54625    20223  2021-03-28 01:00:00  51.88714, -8.56911    NaN
63385     1221  2021-03-28 01:00:00    51.894, -8.51757    NaN
72145     1253  2021-03-28 01:00:00  51.87488, -8.44783    NaN
107185    1258  2021-03-28 01:00:00   51.88229, -8.4076    NaN
115945    1256  2021-03-28 01:00:00  51.88825, -8.39061    NaN
124705    1081  2021-03-28 01:00:00  51.90461, -8.41296    NaN
133465  200811  2021-03-28 01:00:00  51.90523, -8.39022    NaN
142225   20258  2021-03-28 01:00:00  51.90728, -8.35638    NaN
150985   20085  2021-03-28 01:00:00   51.9161, -8.38155    NaN

In [ ]:
for i in df_null.index:
  id = df.loc[i, "id"]
  df.loc[i, "value"] = round(df[(df.id==id) & ((df.datetime=="2021-03-21 01:00:00") | 
                                                 (df.datetime=="2021-03-14 01:00:00") | 
                                                 (df.datetime=="2021-03-07 01:00:00"))]["value"].mean())

In [ ]:
df[df['datetime']=="2021-03-28 01:00:00"]

            id             datetime            location  value
2065      1271  2021-03-28 01:00:00  51.86242, -8.47908   18.0
10825     1716  2021-03-28 01:00:00  51.85265, -8.52882    3.0
19585     1403  2021-03-28 01:00:00  51.87619, -8.49964  127.0
28345     1404  2021-03-28 01:00:00  51.87567, -8.51047   89.0
37105     1405  2021-03-28 01:00:00  51.87281, -8.53436   61.0
45865     1255  2021-03-28 01:00:00  51.87636, -8.56072   56.0
54625    20223  2021-03-28 01:00:00  51.88714, -8.56911   26.0
63385     1221  2021-03-28 01:00:00    51.894, -8.51757   15.0
72145     1253  2021-03-28 01:00:00  51.87488, -8.44783  147.0
80905     1401  2021-03-28 01:00:00  51.87942, -8.43249   21.0
89665     1281  2021-03-28 01:00:00  51.85085, -8.41577   12.0
98425     1283  2021-03-28 01:00:00  51.87578, -8.41266   19.0
107185    1258  2021-03-28 01:00:00   51.88229, -8.4076  107.0
115945    1256  2021-03-28 01:00:00  51.88825, -8.39061  107.0
124705    1081  2021-03-28 01:00:00  51.90461, -8.41296   56.0
133465  200811  2021-03-28 01:00:00  51.90523, -8.39022   70.0
142225   20258  2021-03-28 01:00:00  51.90728, -8.35638   82.0
150985   20085  2021-03-28 01:00:00   51.9161, -8.38155   37.0

In [ ]:
df.datetime = df.datetime.astype("datetime64")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157680 entries, 0 to 157679
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        157680 non-null  int64
 1   datetime  157680 non-null  datetime64[ns]
 2   location  157680 non-null  object
 3   value     157680 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 4.8+ MB

In [ ]:
df

           id            datetime            location  value
0        1271 2021-01-01 00:00:00  51.86242, -8.47908   27.0
1        1271 2021-01-01 01:00:00  51.86242, -8.47908   17.0
2        1271 2021-01-01 02:00:00  51.86242, -8.47908   15.0
3        1271 2021-01-01 03:00:00  51.86242, -8.47908   12.0
4        1271 2021-01-01 04:00:00  51.86242, -8.47908   10.0
...       ...                 ...                 ...    ...
157675  20085 2021-12-31 19:00:00   51.9161, -8.38155  486.0
157676  20085 2021-12-31 20:00:00   51.9161, -8.38155  350.0
157677  20085 2021-12-31 21:00:00   51.9161, -8.38155  202.0
157678  20085 2021-12-31 22:00:00   51.9161, -8.38155  117.0
157679  20085 2021-12-31 23:00:00   51.9161, -8.38155   80.0

[157680 rows x 4 columns]

## Save

In [ ]:
df.to_csv("data_p2.csv", index=False)
!mv /content/data_p2.csv "/content/drive/MyDrive/Khoá luận tốt nghiệp/Dataset"